In [25]:
import pandas as pd
import numpy as np

In [26]:
df = pd.read_csv("C:/Users/tomas/OneDrive/Desktop/DStrabalho/data/processed/enem_completo.csv",
                 sep=";"
                 )

In [27]:
print(df.head(5))

    ANO  COD_MUNICIPIO   MUNICIPIO  COD_UF   UF  DEPENDENCIA_ADM  \
0  2009            NaN         NaN     NaN  NaN              NaN
1  2009      3305752.0      TANGUA    33.0   RJ              2.0
2  2009            NaN         NaN     NaN  NaN              NaN
3  2009            NaN         NaN     NaN  NaN              NaN
4  2009      3304300.0  RIO BONITO    33.0   RJ              3.0

   NOTA_CIENCIAS_NATUREZA  NOTA_CIENCIAS_HUMANAS  NOTA_LINGUAGENS  \
0                   459.6                  410.4            536.6
1                   409.2                  323.1            376.7
2                   406.9                  430.3            519.9
3                   432.3                  527.7            541.2
4                   406.1                  629.9            580.0

   NOTA_MATEMATICA  NOTA_REDACAO RENDA
0            556.9         575.0     B
1            360.5         475.0   NaN
2            413.1         500.0     B
3            464.4         700.0     C
4            417.9         775.0     B

In [34]:
df.shape

(75311038, 13)

In [32]:
df.isnull().sum()

ANO                              0
COD_MUNICIPIO             57454904
MUNICIPIO                 57454904
COD_UF                    57454904
UF                        57454904
DEPENDENCIA_ADM           57454904
NOTA_CIENCIAS_NATUREZA    23403108
NOTA_CIENCIAS_HUMANAS     22526664
NOTA_LINGUAGENS           23656316
NOTA_MATEMATICA           24532760
NOTA_REDACAO              12216421
RENDA                      1962479
MEDIA_NOTA                11717484
dtype: int64

In [29]:
print(df.columns.tolist())

['ANO', 'COD_MUNICIPIO', 'MUNICIPIO', 'COD_UF', 'UF', 'DEPENDENCIA_ADM', 'NOTA_CIENCIAS_NATUREZA', 'NOTA_CIENCIAS_HUMANAS', 'NOTA_LINGUAGENS', 'NOTA_MATEMATICA', 'NOTA_REDACAO', 'RENDA']

In [37]:
Nota_Renda = df.dropna(subset=[ "NOTA_CIENCIAS_NATUREZA",
                       "NOTA_CIENCIAS_HUMANAS",
                       "NOTA_LINGUAGENS",
                       "NOTA_MATEMATICA",
                       "NOTA_REDACAO", 
                       "RENDA" ]                    
                       )

In [38]:
Nota_Renda["MEDIA_NOTA"]=df[["NOTA_CIENCIAS_NATUREZA","NOTA_CIENCIAS_HUMANAS","NOTA_LINGUAGENS","NOTA_MATEMATICA","NOTA_REDACAO"]].mean(axis=1)

In [39]:
print(Nota_Renda.head(5))

    ANO  COD_MUNICIPIO   MUNICIPIO  COD_UF   UF  DEPENDENCIA_ADM  \
0  2009            NaN         NaN     NaN  NaN              NaN
2  2009            NaN         NaN     NaN  NaN              NaN
3  2009            NaN         NaN     NaN  NaN              NaN
4  2009      3304300.0  RIO BONITO    33.0   RJ              3.0
5  2009            NaN         NaN     NaN  NaN              NaN

   NOTA_CIENCIAS_NATUREZA  NOTA_CIENCIAS_HUMANAS  NOTA_LINGUAGENS  \
0                   459.6                  410.4            536.6
2                   406.9                  430.3            519.9
3                   432.3                  527.7            541.2
4                   406.1                  629.9            580.0
5                   430.8                  424.6            457.8

   NOTA_MATEMATICA  NOTA_REDACAO RENDA  MEDIA_NOTA
0            556.9         575.0     B      507.70
2            413.1         500.0     B      454.04
3            464.4         700.0     C      533.12
4            417.9         775.0     B      561.78
5            560.3         625.0     C      499.70

In [40]:
Nota_Renda.to_csv( "Nota_Renda.csv",
    encoding="utf-8",
        sep=";",
        index=False
)

In [41]:
df["MEDIA_NOTA"]=df[["NOTA_CIENCIAS_NATUREZA","NOTA_CIENCIAS_HUMANAS","NOTA_LINGUAGENS","NOTA_MATEMATICA","NOTA_REDACAO"]].mean(axis=1)

In [42]:
df.head()

,ANO,COD_MUNICIPIO,MUNICIPIO,COD_UF,UF,DEPENDENCIA_ADM,NOTA_CIENCIAS_NATUREZA,NOTA_CIENCIAS_HUMANAS,NOTA_LINGUAGENS,NOTA_MATEMATICA,NOTA_REDACAO,RENDA,MEDIA_NOTA
0,2009,NaN,NaN,NaN,NaN,NaN,459.6,410.4,536.6,556.9,575.0,B,507.70
1,2009,3305752.0,TANGUA,33.0,RJ,2.0,409.2,323.1,376.7,360.5,475.0,NaN,388.90
2,2009,NaN,NaN,NaN,NaN,NaN,406.9,430.3,519.9,413.1,500.0,B,454.04
3,2009,NaN,NaN,NaN,NaN,NaN,432.3,527.7,541.2,464.4,700.0,C,533.12
4,2009,3304300.0,RIO BONITO,33.0,RJ,3.0,406.1,629.9,580.0,417.9,775.0,B,561.78

In [43]:
Nota_Estado = df.dropna(subset=[ "NOTA_CIENCIAS_NATUREZA",
                       "NOTA_CIENCIAS_HUMANAS",
                       "NOTA_LINGUAGENS",
                       "NOTA_MATEMATICA",
                       "NOTA_REDACAO", 
                       "RENDA",
                       "COD_MUNICIPIO",
                       "MUNICIPIO",
                       "COD_UF",
                       "UF",
                       "DEPENDENCIA_ADM"
                       ]                    
                       )

In [44]:
Nota_Estado["MEDIA_NOTA"]=df[["NOTA_CIENCIAS_NATUREZA","NOTA_CIENCIAS_HUMANAS","NOTA_LINGUAGENS","NOTA_MATEMATICA","NOTA_REDACAO"]].mean(axis=1)

In [45]:
Nota_Estado.head()

,ANO,COD_MUNICIPIO,MUNICIPIO,COD_UF,UF,DEPENDENCIA_ADM,NOTA_CIENCIAS_NATUREZA,NOTA_CIENCIAS_HUMANAS,NOTA_LINGUAGENS,NOTA_MATEMATICA,NOTA_REDACAO,RENDA,MEDIA_NOTA
4,2009,3304300.0,RIO BONITO,33.0,RJ,3.0,406.1,629.9,580.0,417.9,775.0,B,561.78
7,2009,3304300.0,RIO BONITO,33.0,RJ,3.0,521.4,457.4,557.8,398.9,825.0,C,552.10
10,2009,3304300.0,RIO BONITO,33.0,RJ,4.0,585.6,502.1,376.9,560.0,475.0,.,499.92
19,2009,3304557.0,RIO DE JANEIRO,33.0,RJ,4.0,608.8,616.4,645.1,691.7,575.0,G,627.40
20,2009,3304557.0,RIO DE JANEIRO,33.0,RJ,4.0,624.5,646.7,614.6,658.1,775.0,E,663.78

In [46]:
Nota_Estado.isnull().sum()

ANO                       0
COD_MUNICIPIO             0
MUNICIPIO                 0
COD_UF                    0
UF                        0
DEPENDENCIA_ADM           0
NOTA_CIENCIAS_NATUREZA    0
NOTA_CIENCIAS_HUMANAS     0
NOTA_LINGUAGENS           0
NOTA_MATEMATICA           0
NOTA_REDACAO              0
RENDA                     0
MEDIA_NOTA                0
dtype: int64

In [47]:
Nota_Estado.to_csv( "Nota_Estado.csv",
    encoding="utf-8",
        sep=";",
        index=False
)